### ISSUE TITLE
storybook have some missing dependency

### ISSUE THREAD

**Issue by matart15** [nstaldev/nstal#3]
I had to add this 3 library to run storybook

packages/react-components/package.json
```json
    "@emotion/styled": "11.9.3",
    "@emotion/react": "11.9.3",
    "framer-motion": "6.5.1",
```

if you want I will send PR

**Comment by phbernard** [comment]
Oops! Yes a PR would be great!

**Comment by matart15** [comment]
🙇 https://github.com/nstaldev/nstal/pull/11
